spring:
  jmx:
    enabled: true
  datasource:
    url: 'jdbc:h2:mem:db'
    username: 'sa'
    password: 'sa'
  jpa:
    properties:
      hibernate:
        "globally_quoted_identifiers": "true"
  webflux:
    base-path: /
logging:
  level:
    root: warn
    org.springframework.security: warn
    tech.shali.automission: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
