spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        hbm2ddl:
          auto: update
    open-in-view: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mail:
    host: smtp.qq.com
    username: none  # IDE 问题似乎识别不到dev中的配置，在此做占位符配置，被active配置覆盖
    password: none
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
  task:
    scheduling:
      pool:
        size: 10

server:
  servlet:
    context-path: /auto-mission

logging:
  level:
    root: warn
    tech.shali: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
  file:
    name: log/log.log
